import type { RuntimeCurvatureEnvelope, RuntimeInstabilityDensityEnvelope, RuntimeSingularityEnvelope, RuntimeTensorEnvelope, RuntimeTopologyGeometry, TensorCertification, TensorNode, TensorRisk } from './tensorTypes';
export interface TensorGuardViolation extends TensorRisk { readonly envelopeId?: string; }
export function assertTensorReadonly(nodes: readonly TensorNode[]): TensorGuardViolation[] { const out: TensorGuardViolation[] = []; for (const n of nodes) { if (n.liveExecutionEnabled !== false || n.retryEnabled !== false || n.backgroundEnabled !== false || n.realUsersAllowed !== false || n.stage !== 'STAGE_0_READ_ONLY') out.push({ code: 'TENSOR_READONLY_INVARIANT_BROKEN', severity: 'critical', description: `node ${n.id} viola invariantes` }); } return out; }
export function assertTensorDeterminism(a: string, b: string): TensorGuardViolation[] { return a === b ? [] : [{ code: 'TENSOR_NON_DETERMINISTIC', severity: 'error', description: 'assinaturas divergentes' }]; }
export function assertNoTensorMutation(before: RuntimeTensorEnvelope, after: RuntimeTensorEnvelope): TensorGuardViolation[] { if (before === after) return []; if (before.tensor.signature !== after.tensor.signature) return [{ code: 'TENSOR_MUTATION_DETECTED', severity: 'critical', description: 'envelope mutado' }]; return []; }
export function assertNoUnboundedCurvature(c: RuntimeCurvatureEnvelope): TensorGuardViolation[] { return c.unbounded ? [{ code: 'TENSOR_CURVATURE_UNBOUNDED', severity: 'critical', description: 'curvatura ilimitada' }] : []; }
export function assertNoCriticalDensity(d: RuntimeInstabilityDensityEnvelope): TensorGuardViolation[] { return d.level === 'CRITICAL' ? [{ code: 'TENSOR_DENSITY_CRITICAL', severity: 'critical', description: 'densidade crítica' }] : []; }
export function assertNoTopologyCollapse(t: RuntimeTopologyGeometry): TensorGuardViolation[] { return t.collapsing ? [{ code: 'TENSOR_TOPOLOGY_COLLAPSED', severity: 'critical', description: 'topologia colapsando' }] : []; }
export function assertNoTerminalSingularity(s: RuntimeSingularityEnvelope): TensorGuardViolation[] { return s.terminal ? [{ code: 'TENSOR_SINGULARITY_TERMINAL', severity: 'critical', description: 'singularidade terminal' }] : []; }
export function assertTensorCertificationIntegrity(c: TensorCertification): TensorGuardViolation[] { return c.safe ? [] : [{ code: 'TENSOR_CERTIFICATION_INVALID', severity: c.rank === 'BLOCKED' ? 'critical' : 'error', description: c.reasons.join(',') || 'unsafe' }]; }
