import type { ManifoldCertification, ManifoldNode, ManifoldRisk, RuntimeContinuityEnvelope, RuntimeContinuumSingularity, RuntimeDeformationContinuum, RuntimeManifoldEnvelope, RuntimePropagationGeodesic } from './manifoldTypes';
export interface ManifoldGuardViolation extends ManifoldRisk { readonly envelopeId?: string; }
export function assertManifoldReadonly(nodes: readonly ManifoldNode[]): ManifoldGuardViolation[] { const out: ManifoldGuardViolation[] = []; for (const n of nodes) { if (n.liveExecutionEnabled !== false || n.retryEnabled !== false || n.backgroundEnabled !== false || n.realUsersAllowed !== false || n.stage !== 'STAGE_0_READ_ONLY') out.push({ code: 'MANIFOLD_READONLY_INVARIANT_BROKEN', severity: 'critical', description: `node ${n.id} viola invariantes` }); } return out; }
export function assertManifoldDeterminism(a: string, b: string): ManifoldGuardViolation[] { return a === b ? [] : [{ code: 'MANIFOLD_NON_DETERMINISTIC', severity: 'error', description: 'assinaturas divergentes' }]; }
export function assertNoManifoldMutation(before: RuntimeManifoldEnvelope, after: RuntimeManifoldEnvelope): ManifoldGuardViolation[] { if (before === after) return []; if (before.manifold.signature !== after.manifold.signature) return [{ code: 'MANIFOLD_MUTATION_DETECTED', severity: 'critical', description: 'envelope mutado' }]; return []; }
export function assertNoInfiniteGeodesics(g: RuntimePropagationGeodesic): ManifoldGuardViolation[] { return g.infinite ? [{ code: 'MANIFOLD_GEODESIC_INFINITE', severity: 'critical', description: 'geodésica infinita' }] : []; }
export function assertNoContinuityCollapse(c: RuntimeContinuityEnvelope): ManifoldGuardViolation[] { return c.class === 'COLLAPSED' ? [{ code: 'MANIFOLD_CONTINUITY_COLLAPSED', severity: 'critical', description: 'continuidade colapsada' }] : []; }
export function assertNoIrreversibleDeformation(d: RuntimeDeformationContinuum): ManifoldGuardViolation[] { return d.irreversible ? [{ code: 'MANIFOLD_DEFORMATION_IRREVERSIBLE', severity: 'critical', description: 'deformação irreversível' }] : []; }
export function assertNoTerminalContinuumSingularity(s: RuntimeContinuumSingularity): ManifoldGuardViolation[] { return s.terminal ? [{ code: 'MANIFOLD_SINGULARITY_TERMINAL', severity: 'critical', description: 'singularidade terminal' }] : []; }
export function assertManifoldCertificationIntegrity(c: ManifoldCertification): ManifoldGuardViolation[] { return c.safe ? [] : [{ code: 'MANIFOLD_CERTIFICATION_INVALID', severity: c.rank === 'BLOCKED' ? 'critical' : 'error', description: c.reasons.join(',') || 'unsafe' }]; }
