export type ManifoldStabilityClass = 'STABLE' | 'CONTINUOUS' | 'DISTORTED' | 'FRACTURED' | 'SINGULAR';
export type ContinuityClass = 'CONTINUOUS' | 'WEAKLY_CONTINUOUS' | 'DISCONTINUOUS' | 'FRACTURED' | 'COLLAPSED';
export type GeodesicPropagation = 'MINIMAL' | 'CONTAINED' | 'DISTRIBUTED' | 'ESCALATING' | 'INFINITE';
export type DeformationContinuum = 'NONE' | 'ELASTIC' | 'DISTRIBUTED' | 'FRACTURED' | 'IRREVERSIBLE';
export type ContinuumSingularity = 'NONE' | 'LOCAL' | 'DISTRIBUTED' | 'RECURSIVE' | 'TERMINAL';
export type ManifoldSeverity = 'info' | 'warn' | 'error' | 'critical';
export interface ManifoldNode { readonly id: string; readonly layer: string; readonly stage: string; readonly liveExecutionEnabled: boolean; readonly retryEnabled: boolean; readonly backgroundEnabled: boolean; readonly realUsersAllowed: boolean; readonly position: number; readonly tension: number; readonly elasticity: number; readonly neighbors: readonly string[]; readonly signature: string; }
export interface RuntimeStabilityContinuum { readonly nodes: readonly ManifoldNode[]; readonly pressure: number; readonly balance: number; readonly collapsed: boolean; readonly signature: string; }
export interface RuntimeEquilibriumManifold { readonly field: readonly number[]; readonly symmetry: number; readonly normalized: boolean; readonly unstable: boolean; readonly signature: string; }
export interface RuntimeContinuityEnvelope { readonly class: ContinuityClass; readonly strength: number; readonly fractured: boolean; readonly breaks: number; }
export interface RuntimePropagationGeodesic { readonly propagation: GeodesicPropagation; readonly length: number; readonly containment: number; readonly recursive: boolean; readonly infinite: boolean; }
export interface RuntimeContinuityMetric { readonly score: number; readonly stable: boolean; readonly distribution: readonly number[]; readonly equilibrium: number; }
export interface RuntimeDeformationContinuum { readonly deformation: DeformationContinuum; readonly pressure: number; readonly elastic: boolean; readonly irreversible: boolean; }
export interface RuntimeContinuumSingularity { readonly class: ContinuumSingularity; readonly spread: number; readonly recursive: boolean; readonly terminal: boolean; }
export interface RuntimeManifoldCollapse { readonly collapsing: boolean; readonly cascade: boolean; readonly irrecoverable: boolean; readonly propagation: number; }
export interface ManifoldRisk { readonly code: string; readonly severity: ManifoldSeverity; readonly description: string; }
export interface ManifoldCertification { readonly safe: boolean; readonly confidence: number; readonly rank: 'OK' | 'WARN' | 'BLOCKED'; readonly reasons: readonly string[]; }
export interface RuntimeManifoldEnvelope { readonly id: string; readonly continuum: RuntimeStabilityContinuum; readonly manifold: RuntimeEquilibriumManifold; readonly continuity: RuntimeContinuityEnvelope; readonly geodesic: RuntimePropagationGeodesic; readonly metric: RuntimeContinuityMetric; readonly deformation: RuntimeDeformationContinuum; readonly singularity: RuntimeContinuumSingularity; readonly collapse: RuntimeManifoldCollapse; readonly classification: ManifoldStabilityClass; readonly certification: ManifoldCertification; readonly risks: readonly ManifoldRisk[]; readonly score: number; readonly stable: boolean; }
export interface RuntimeManifoldAggregate { readonly envelopes: readonly RuntimeManifoldEnvelope[]; readonly score: number; readonly confidence: number; readonly worstSeverity: ManifoldSeverity; readonly worstContinuity: ContinuityClass; readonly worstGeodesic: GeodesicPropagation; readonly worstDeformation: DeformationContinuum; readonly worstSingularity: ContinuumSingularity; readonly stable: boolean; readonly risks: readonly ManifoldRisk[]; }
