export type SponsorActivationInvariant =
  | 'AC-LAYER-READ-ONLY-CONSUMPTION'
  | 'AC-LAYER-ACTIVATION-DETERMINISM'
  | 'AC-LAYER-PREREQUISITE-COMPLETENESS'
  | 'AC-LAYER-GATE-CANONICAL-ORDERING'
  | 'AC-LAYER-ROLLOUT-CONSTRAINT-INTEGRITY'
  | 'AC-LAYER-OPERATIONAL-READINESS-PROOF'
  | 'AC-LAYER-NO-RUNTIME-ACTIVATION'
  | 'AC-LAYER-IMMUTABLE-LINEAGE'
  | 'AC-TERMINAL-ACTIVATION-READINESS-CERTIFICATION';

export const ACTIVATION_INVARIANTS: ReadonlyArray<SponsorActivationInvariant> = Object.freeze([
  'AC-LAYER-READ-ONLY-CONSUMPTION',
  'AC-LAYER-ACTIVATION-DETERMINISM',
  'AC-LAYER-PREREQUISITE-COMPLETENESS',
  'AC-LAYER-GATE-CANONICAL-ORDERING',
  'AC-LAYER-ROLLOUT-CONSTRAINT-INTEGRITY',
  'AC-LAYER-OPERATIONAL-READINESS-PROOF',
  'AC-LAYER-NO-RUNTIME-ACTIVATION',
  'AC-LAYER-IMMUTABLE-LINEAGE',
  'AC-TERMINAL-ACTIVATION-READINESS-CERTIFICATION',
]);

export function generateActivationInvariants(): ReadonlyArray<SponsorActivationInvariant> {
  return ACTIVATION_INVARIANTS;
}
